AlignParameters:
  Enabled: false
Encoding:
  Enabled: false
HashSyntax:
  Enabled: false
LineLength:
  Enabled: false
ConditionalAssignment: 
  Enabled: false
IfInsideElse:
  Enabled: false
SignalException: 
  Enabled: false
MethodLength:
  Max: 30
AllCops:
  Exclude:
    - 'libraries/hf_lamp.rb'
